In [1]:
#import dependencies
import csv
import pandas as pd

In [2]:
#reading in traffic data from csv
Csvpath = "US_Accidents_Dec19.csv"
traffic_data = pd.read_csv(Csvpath)
traffic_data.head()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
#Finding all column names in traffic dataframe
traffic_data.columns

Index(['ID', 'Source', 'TMC', 'Severity', 'Start_Time', 'End_Time',
       'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)',
       'Description', 'Number', 'Street', 'Side', 'City', 'County', 'State',
       'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Weather_Timestamp',
       'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)',
       'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [5]:
#updating dataframe to keep only columns we need
traffic_data_reorg = traffic_data[["Severity", "Description", "Start_Time", "Start_Lat","Start_Lng","Street", "Zipcode", "City","County","State","Visibility(mi)"]]
traffic_data_reorg.head(30)

,Severity,Description,Start_Time,Start_Lat,Start_Lng,Street,Zipcode,City,County,State,Visibility(mi)
0,3,Right lane blocked due to accident on I-70 Eas...,2016-02-08 05:46:00,39.865147,-84.058723,I-70 E,45424,Dayton,Montgomery,OH,10.0
1,2,Accident on Brice Rd at Tussing Rd. Expect del...,2016-02-08 06:07:59,39.928059,-82.831184,Brice Rd,43068-3402,Reynoldsburg,Franklin,OH,10.0
2,2,Accident on OH-32 State Route 32 Westbound at ...,2016-02-08 06:49:27,39.063148,-84.032608,State Route 32,45176,Williamsburg,Clermont,OH,10.0
3,3,Accident on I-75 Southbound at Exits 52 52B US...,2016-02-08 07:23:34,39.747753,-84.205582,I-75 S,45417,Dayton,Montgomery,OH,9.0
4,2,Accident on McEwen Rd at OH-725 Miamisburg Cen...,2016-02-08 07:39:07,39.627781,-84.188354,Miamisburg Centerville Rd,45459,Dayton,Montgomery,OH,6.0
5,3,Accident on I-270 Outerbelt Northbound near Ex...,2016-02-08 07:44:26,40.100590,-82.925194,Westerville Rd,43081,Westerville,Franklin,OH,7.0
6,2,Accident on Oakridge Dr at Woodward Ave. Expec...,2016-02-08 07:59:35,39.758274,-84.230507,N Woodward Ave,45417-2476,Dayton,Montgomery,OH,7.0
7,3,Accident on I-75 Southbound at Exit 54B Grand ...,2016-02-08 07:59:58,39.770382,-84.194901,N Main St,45405,Dayton,Montgomery,OH,7.0
8,2,Accident on Notre Dame Ave at Warner Ave. Expe...,2016-02-08 08:00:40,39.778061,-84.172005,Notre Dame Ave,45404-1923,Dayton,Montgomery,OH,5.0
9,3,Right hand shoulder blocked due to accident on...,2016-02-08 08:10:04,40.100590,-82.925194,Westerville Rd,43081,Westerville,Franklin,OH,3.0
10,3,Accident on I-270 Outerbelt Northbound at Exit...,2016-02-08 08:14:42,39.952812,-83.119293,Outerbelt S,43228,Columbus,Franklin,OH,5.0
11,3,One lane blocked due to accident on I-70 Westb...,2016-02-08 08:21:27,39.932709,-82.830910,I-70 E,43068,Reynoldsburg,Franklin,OH,3.0
12,2,Accident on Revere Ave at Watervliet Ave. Expe...,2016-02-08 08:36:34,39.737633,-84.149933,Watervliet Ave,45420-1863,Dayton,Montgomery,OH,3.0
13,2,Accident on Salem Ave at Hillcrest Ave / Kensi...,2016-02-08 08:37:07,39.790760,-84.241547,Salem Ave,45406-2708,Dayton,Montgomery,OH,10.0
14,2,Accident on OH-16 Broad St at James Rd. Expect...,2016-02-08 08:39:43,39.972038,-82.913521,E Broad St,43213-1006,Columbus,Franklin,OH,3.0
15,2,Accident on Wayne Ave at Glencoe Ave. Expect d...,2016-02-08 08:43:20,39.745888,-84.170410,Glencoe Ave,45410-1721,Dayton,Montgomery,OH,3.0
16,2,Accident on James H McGee Blvd at US-35. Expec...,2016-02-08 08:53:17,39.748329,-84.224007,S James H McGee Blvd,45402,Dayton,Montgomery,OH,7.0
17,2,Accident on Delphos Ave at Brooklyn Ave. Expec...,2016-02-08 09:24:37,39.752174,-84.239952,Delphos Ave,45417-1727,Dayton,Montgomery,OH,10.0
18,2,Accident on Stewart St near Rubicon St. Expect...,2016-02-08 09:25:17,39.740669,-84.184135,Rubicon St,45409-2659,Dayton,Montgomery,OH,10.0
19,2,Accident on Hillcrest Ave at Piccadilly Ave. E...,2016-02-08 09:35:35,39.790703,-84.244461,W Hillcrest Ave,45406-2640,Dayton,Montgomery,OH,10.0
20,2,Accident on Brookhill Dr at Glenhurst Ct.,2016-02-08 10:11:15,40.052509,-82.882332,Brookhill Dr,43230-1765,Columbus,Franklin,OH,2.0
21,2,Accident on Princeton Dr at Catalpa Dr. Expect...,2016-02-08 10:24:27,39.773346,-84.224686,Princeton Dr,45406-4736,Dayton,Montgomery,OH,10.0
22,2,Accident on OH-741 Springboro Pike at Lyons Rd...,2016-02-08 11:53:19,39.628288,-84.226151,Springboro Pike,45342,Miamisburg,Montgomery,OH,6.0
23,3,Accident on I-71 Northbound at Exit 113 Silver...,2016-02-08 12:00:00,40.023487,-82.994888,North Fwy S,43211,Columbus,Franklin,OH,8.0
24,2,Accident on Hoover Ave at Elmhurst Rd.,2016-02-08 12:16:44,39.761379,-84.259216,Hoover Ave,45417-1117,Dayton,Montgomery,OH,10.0
25,2,Accident on County Hwy-16 Sportsman Club Rd be...,2016-02-08 12:41:08,40.158024,-82.641762,Sportsman Club Rd,43031-9133,Johnstown,Licking,OH,5.0
26,2,Accident on Irving Ave at Wilmington Ave.,2016-02-08 12:52:05,39.733219,-84.159653,Irving Ave,45419-4148,Dayton,Montgomery,OH,7.0
27,2,Accident on Helena St at OH-48 Main St.,2016-02-08 14:24:48,39.775303,-84.200523,W Helena St,45405-4326,Dayton,Montgomery,OH,10.0
28,2,Accident on Salem Ave at Litchfield Ave.,2016-02-08 14:56:57,39.789322,-84.239105,Litchfield Ave,45406-2701,Dayton,Montgomery,OH,10.0
29,2,Accident on 4th St at Wayne Ave.,2016-02-08 15:26:14,39.758720,-84.183762,E 4th St,45402,Dayton,Montgomery,OH,10.0

In [9]:
#Narrowing down dataframe to only show Atlanta, Georgia accidents from 2019
date = '2019-01-01 00:00:00'
atl_data = traffic_data_reorg.loc[(traffic_data_reorg["State"]=="GA")
                                  &(traffic_data_reorg["City"]=="Atlanta")
                                  &(traffic_data_reorg["Start_Time"]>=date),:]
atl_data

,Severity,Description,Start_Time,Start_Lat,Start_Lng,Street,Zipcode,City,County,State,Visibility(mi)
512404,3,Three right lane blocked and right hand should...,2019-12-25 11:35:57,33.912956,-84.391212,GA-407 E,30342,Atlanta,Fulton,GA,10.0
512416,3,Accident on I-75 Northbound after 17th St.,2019-12-25 18:33:34,33.791977,-84.392410,GA-401 S,30363,Atlanta,Fulton,GA,10.0
512417,3,Two lane blocked and right hand shoulder block...,2019-12-25 18:55:24,33.791977,-84.392410,GA-401 S,30363,Atlanta,Fulton,GA,10.0
512419,3,Four lanes blocked and left hand shoulder bloc...,2019-12-25 20:56:05,33.783630,-84.495560,GA-407 S,30318,Atlanta,Fulton,GA,10.0
512430,3,Right lane blocked and right hand shoulder blo...,2019-12-25 15:08:13,33.652176,-84.367058,GA-407 W,30354,Atlanta,Fulton,GA,10.0
...,...,...,...,...,...,...,...,...,...,...,...
2973560,2,At US-41/Paces Ferry Rd/Exit 255 - Accident. L...,2019-08-22 17:00:47,33.843640,-84.429720,I-75 N,30327,Atlanta,Fulton,GA,10.0
2973984,4,At GA-166/Lakewood Fwy/Exit 5 - Accident.,2019-08-23 02:01:46,33.686550,-84.499870,GA-407 N,30331,Atlanta,Fulton,GA,10.0
2974006,2,At Shallowford Rd/Exit 93 - Accident. Right la...,2019-08-23 19:05:00,33.868000,-84.285130,GA-403 S,30341,Atlanta,DeKalb,GA,10.0
2974010,2,At Chamblee Dunwoody Rd/Exit 30 - Accident. Ce...,2019-08-23 20:43:54,33.920200,-84.320150,I-285 E,30319,Atlanta,DeKalb,GA,10.0
2974013,2,Between I-285/Exit 95 and Pleasantdale Rd/Exit...,2019-08-23 20:29:30,33.895722,-84.252706,GA-403 N,30340,Atlanta,DeKalb,GA,10.0